### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by ShKlinkenberg** [Oefenweb/r-database#2]
I can't get this connection working. The documentation is too por and there are no examples. It's just trail and error to get this working.

Let's update the documentation

**Comment by tersmitten** [comment]
Have you installed the package, it has nice documentation (see `?oefenwebDatabase::connect` for instance). This package is only a thin wrapper around `DBI` and `RMySQL` that forces the use `~/.my.cnf` which is a best practice for connecting. This way you don't have to store credential in you `R` scripts.

So the `~/.my.cnf` is leading, if you have `host = 127.0.0.1` in it, `R` will will connect to `127.0.0.1` (your machine). If you put put an external ip address in it will connect to that.

In your case you're probably trying to use it to connect to the research server, to be able to do that you need that be "on" the research server (e.g. `rstudio-server`).

I hope this answers the questions you have.

**Comment by tersmitten** [comment]
If you have any ideas on improving the documentation feel free to open a pull request.

**Comment by ShKlinkenberg** [comment]
It would be clearer to have the README state that this only works on the oefenweb research server.

A few pointers in the readme would be nice. Mind if I add it directly to the repo?

**Comment by tersmitten** [comment]
The package works fine on any machine as long as you make sure that you have a working `~/.my.cnf`.

**Comment by ShKlinkenberg** [comment]
than what would the hostname be? Maybe this is not the place to discuss this.

**Comment by tersmitten** [comment]
The same as you use to connect to adminer. However, Mysql is not exposed to the internet so that won't work ☹️.
